(()=>{
'use strict';
const VERSION='3.0.0',PKEY='bf.profile',GKEY='bf.gallery',LKEY='bf.leaderboard',RKEY='bf.replay';
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
const txt=(en,ro)=>state.lang==='ro'?ro:en;
let profile=JSON.parse(localStorage.getItem(PKEY)||'null')||{name:'Architect',xp:0,level:1,avatar:'🧱',badges:[],settings:{contrast:false,large:false,motion:false,focus:true,music:false}};
let replay=[],replayTimer=null,installPrompt=null,blueprint=[],procedural=null;
const saveProfile=()=>{profile.level=1+Math.floor(profile.xp/500);localStorage.setItem(PKEY,JSON.stringify(profile))};
const addXP=n=>{profile.xp+=n;saveProfile();paintPremium()};
const unlock=(id,label)=>{if(profile.badges.includes(id))return;profile.badges.push(id);saveProfile();toast(`🏅 ${label}`)};
function inject(){
 document.head.insertAdjacentHTML('beforeend','<link rel="manifest" href="./manifest.webmanifest"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="mobile-web-app-capable" content="yes">');
 const chip=document.createElement('span');chip.className='version-chip';chip.textContent='v'+VERSION;q('.top-actions')?.prepend(chip);
 ['blueprint','puzzle','boss'].forEach((m,i)=>{const b=document.createElement('button');b.type='button';b.dataset.mode=m;b.innerHTML=[`📐 <span>${txt('Blueprint','Schiță')}</span>`,`🧩 <span>${txt('Puzzle','Puzzle')}</span>`,`👹 <span>${txt('Boss','Boss')}</span>`][i];q('#modeTabs')?.append(b)});
 document.body.insertAdjacentHTML('beforeend',`<div class="premium-dock"><button type="button" data-premium="profile" aria-label="Profile">👤</button><button type="button" data-premium="studio" aria-label="Studio">🧰</button><button type="button" data-premium="access" aria-label="Accessibility">♿</button><button type="button" data-premium="news" aria-label="What's new">✨</button></div><aside class="premium-panel" id="premiumPanel"></aside>`);
 qa('[data-premium]').forEach(b=>b.onclick=()=>openPanel(b.dataset.premium));
 q('#modeTabs').addEventListener('click',e=>{const b=e.target.closest('[data-mode]');if(!b)return;if(['blueprint','puzzle','boss'].includes(b.dataset.mode)){setPremiumMode(b.dataset.mode)}});
 wrapGame();registerPWA();applyAccess();onboarding();gamepad();
}
function wrapGame(){
 const oldSnapshot=window.snapshot;window.snapshot=function(){oldSnapshot();replay.push({t:Date.now(),scene:state.scene.map(b=>({...b})),mode:state.mode});if(replay.length>120)replay.shift();localStorage.setItem(RKEY,JSON.stringify(replay))};
 const oldFinish=window.finishRun;window.finishRun=function(){oldFinish();const score=state.score||calcScore();recordScore(score);addXP(Math.max(25,Math.round(score/25)));evaluateAchievements()};
 const oldRender=window.render;window.render=function(){oldRender();drawBlueprint();evaluateAchievements()};
}
function setPremiumMode(m){state.mode=m;state.running=false;qa('#modeTabs [data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));if(m==='blueprint')startBlueprint();if(m==='puzzle')startPuzzle();if(m==='boss')startBoss();render()}
function startBlueprint(){blueprint=generateShape(10);state.scene=[];state.gravity=true;toast(txt('Match the glowing blueprint.','Reproduce schița luminoasă.'))}
function startPuzzle(){state.scene=[];const shape=generateShape(16);shape.slice(0,11).forEach(p=>state.scene.push({id:++uid,x:p.x,y:p.y,z:p.z,type:'core',hp:type('core').hp}));blueprint=shape;toast(txt('Repair the missing blocks.','Repară blocurile lipsă.'))}
function startBoss(){state.scene=[];for(let x=2;x<6;x++)for(let y=2;y<6;y++)for(let z=0;z<Math.max(1,6-Math.abs(x-3.5)-Math.abs(y-3.5));z++)state.scene.push({id:++uid,x,y,z,type:z===0?'void':(z>3?'ember':'core'),hp:type(z===0?'void':(z>3?'ember':'core')).hp});state.tool='meteor';blueprint=[];toast(txt('Destroy the weak glowing crown.','Distruge coroana vulnerabilă.'))}
function generateShape(n){let seed=(new Date().getDate()*97+state.level*31)%997;const out=[];for(let i=0;i<n;i++){seed=(seed*37+17)%997;const x=2+(seed%4),y=2+(Math.floor(seed/7)%4),z=Math.min(5,out.filter(p=>p.x===x&&p.y===y).length);out.push({x,y,z})}procedural={seed,n};return out}
function drawBlueprint(){let o=q('.blueprint-overlay');if(!o){o=document.createElement('div');o.className='blueprint-overlay';q('#stage')?.append(o)}o.innerHTML='';if(!['blueprint','puzzle'].includes(state.mode))return;blueprint.forEach(p=>{if(at(p.x,p.y,p.z))return;const d=document.createElement('i');d.className='blueprint-cell';d.style.left=(50+(p.x-3.5)*6.2)+'%';d.style.top=(58+(p.y-3.5)*3.2-p.z*3.5)+'%';o.append(d)})}
function blueprintAccuracy(){if(!blueprint.length)return 0;const hit=blueprint.filter(p=>at(p.x,p.y,p.z)).length;return Math.round(hit/blueprint.length*100)}
function openPanel(kind){const p=q('#premiumPanel');p.classList.add('open');p.dataset.kind=kind;paintPremium()}
function paintPremium(){const p=q('#premiumPanel');if(!p?.classList.contains('open'))return;const kind=p.dataset.kind;
 if(kind==='profile')p.innerHTML=profileHTML();
 if(kind==='studio')p.innerHTML=studioHTML();
 if(kind==='access')p.innerHTML=accessHTML();
 if(kind==='news')p.innerHTML=newsHTML();
 bindPanel();
}
function profileHTML(){const board=getBoard().slice(0,8);return `<h2>${profile.avatar} ${esc(profile.name)} · Lv.${profile.level}</h2><div class="premium-card"><b>${profile.xp} XP</b><small>${txt('Next level','Nivel următor')}: ${profile.level*500} XP</small></div><h3>${txt('Profile','Profil')}</h3><div class="premium-row"><input id="profileName" value="${esc(profile.name)}" maxlength="24"><select id="avatar"><option>🧱</option><option>🤖</option><option>🏗️</option><option>👷</option><option>⚡</option></select></div><button data-pact="saveProfile">${txt('Save profile','Salvează profilul')}</button><h3>${txt('Achievements','Realizări')}</h3><div class="badge-list">${achievements().map(a=>`<span class="achievement ${profile.badges.includes(a.id)?'unlocked':''}">${a.icon} ${a.label}</span>`).join('')}</div><h3>${txt('Leaderboard','Clasament')}</h3>${board.map((r,i)=>`<div class="premium-card"><b>#${i+1} ${esc(r.name)} · ${r.score}</b><small>${new Date(r.date).toLocaleDateString()}</small></div>`).join('')||'<small>No scores yet</small>'}`}
function studioHTML(){const gallery=getGallery();return `<h2>${txt('Creator Studio','Studio Creator')}</h2><div class="premium-grid three"><button data-pact="blueprint">📐 ${txt('Blueprint','Schiță')}</button><button data-pact="puzzle">🧩 Puzzle</button><button data-pact="boss">👹 Boss</button><button data-pact="ai">🤖 AI Architect</button><button data-pact="procedural">🎲 ${txt('Generate level','Generează nivel')}</button><button data-pact="png">🖼️ PNG</button><button data-pact="share">🔗 Share</button><button data-pact="import">📥 Import</button><button data-pact="replay">⏯ Replay</button></div><input id="importFile" type="file" accept="application/json" hidden><h3>${txt('Gallery','Galerie')}</h3><div class="premium-grid">${[0,1,2,3,4,5].map(i=>`<div class="premium-card"><div class="gallery-thumb">${gallery[i]?'🏰':'＋'}</div><b>${gallery[i]?esc(gallery[i].name):txt('Empty slot','Slot gol')}</b><div class="premium-row"><button data-slot-save="${i}">💾</button><button data-slot-load="${i}" ${gallery[i]?'':'disabled'}>📂</button></div></div>`).join('')}</div><h3>AI report</h3><div class="premium-card ai-report" id="aiReport">${txt('Analyze your tower to receive structural advice.','Analizează turnul pentru recomandări structurale.')}</div>`}
function accessHTML(){return `<h2>${txt('Accessibility','Accesibilitate')}</h2>${toggle('contrast',txt('High contrast','Contrast ridicat'))}${toggle('large',txt('Large text','Text mărit'))}${toggle('motion',txt('Reduce motion','Reducere mișcare'))}${toggle('focus',txt('Visible keyboard focus','Focus vizibil'))}${toggle('music',txt('Adaptive ambient sound','Sunet ambiental adaptiv'))}<h3>${txt('Keyboard','Tastatură')}</h3><div class="premium-card"><small>B/D/C modes · G gravity · Delete remove · Ctrl+Z undo · Esc photo mode</small></div><button data-pact="install">📲 ${txt('Install app','Instalează aplicația')}</button>`}
function newsHTML(){return `<h2>BlockForge ${VERSION}</h2><ul class="whats-new"><li>PWA + offline mode</li><li>Blueprint, Puzzle and Boss modes</li><li>Profile, XP, achievements and gallery</li><li>Replay, share codes and JSON import</li><li>Procedural levels and AI Architect</li><li>Gamepad, adaptive audio and accessibility</li><li>Mobile-first creator dock</li></ul>`}
function toggle(k,label){return `<label class="premium-card premium-row"><span>${label}</span><input type="checkbox" data-setting="${k}" ${profile.settings[k]?'checked':''}></label>`}
function bindPanel(){q('#profileName')&& (q('#avatar').value=profile.avatar);qa('[data-pact]').forEach(b=>b.onclick=()=>panelAction(b.dataset.pact));qa('[data-setting]').forEach(i=>i.onchange=()=>{profile.settings[i.dataset.setting]=i.checked;saveProfile();applyAccess()});qa('[data-slot-save]').forEach(b=>b.onclick=()=>saveSlot(+b.dataset.slotSave));qa('[data-slot-load]').forEach(b=>b.onclick=()=>loadSlot(+b.dataset.slotLoad));q('#importFile')?.addEventListener('change',importJSON)}
function panelAction(a){if(['blueprint','puzzle','boss'].includes(a)){setPremiumMode(a);q('#premiumPanel').classList.remove('open')}if(a==='saveProfile'){profile.name=q('#profileName').value.trim()||'Architect';profile.avatar=q('#avatar').value;saveProfile();paintPremium()}if(a==='ai')analyze();if(a==='procedural'){state.level=Math.floor(Math.random()*10);startBlueprint();render();toast('Seed '+procedural.seed)}if(a==='png')exportPNG();if(a==='share')shareScene();if(a==='import')q('#importFile').click();if(a==='replay')playReplay();if(a==='install')installApp()}
function analyze(){const h=Math.max(0,...state.scene.map(b=>b.z+1)),unst=unstableCount(),mass=state.scene.reduce((s,b)=>s+type(b.type).mass,0),bases=state.scene.filter(b=>b.z===0).length;const tips=[];if(bases<4)tips.push(txt('Widen the foundation to at least four blocks.','Lărgește fundația la minimum patru blocuri.'));if(unst)tips.push(txt(`${unst} unsupported blocks need support.`,`${unst} blocuri fără suport trebuie stabilizate.`));if(mass>state.scene.length*2.8)tips.push(txt('Move heavy blocks lower.','Mută blocurile grele mai jos.'));if(h>=5&&unst===0)tips.push(txt('Excellent tall and stable structure.','Structură înaltă și stabilă excelentă.'));if(!tips.length)tips.push(txt('Add height or test the structure with a controlled impact.','Adaugă înălțime sau testează structura cu un impact controlat.'));q('#aiReport').textContent=`${txt('Height','Înălțime')}: ${h}\n${txt('Mass','Masă')}: ${mass}\n${txt('Blueprint accuracy','Precizie schiță')}: ${blueprintAccuracy()}%\n\n• ${tips.join('\n• ')}`}
function achievements(){return [{id:'stable',icon:'🏛️',label:txt('Perfect Stability','Stabilitate perfectă')},{id:'combo',icon:'💥',label:txt('Chain Reaction','Reacție în lanț')},{id:'height',icon:'🏙️',label:txt('Sky Builder','Constructor de nori')},{id:'budget',icon:'🪙',label:txt('No Waste','Fără risipă')},{id:'boss',icon:'👑',label:txt('Boss Breaker','Învingător Boss')},{id:'gallery',icon:'🎨',label:txt('Curator','Curator')}];}
function evaluateAchievements(){const h=Math.max(0,...state.scene.map(b=>b.z+1));if(state.scene.length&&unstableCount()===0)unlock('stable',achievements()[0].label);if(state.maxCombo>=3)unlock('combo',achievements()[1].label);if(h>=7)unlock('height',achievements()[2].label);if(state.running&&state.budget===0)unlock('budget',achievements()[3].label);if(state.mode==='boss'&&state.scene.length<5)unlock('boss',achievements()[4].label);if(getGallery().filter(Boolean).length>=3)unlock('gallery',achievements()[5].label)}
function getGallery(){return JSON.parse(localStorage.getItem(GKEY)||'[]')}function saveSlot(i){const g=getGallery();g[i]={name:`Build ${i+1}`,date:Date.now(),scene:state.scene.map(b=>({...b}))};localStorage.setItem(GKEY,JSON.stringify(g));addXP(40);paintPremium()}function loadSlot(i){const g=getGallery();if(!g[i])return;snapshot();state.scene=g[i].scene.map(b=>({...b,id:++uid}));render();q('#premiumPanel').classList.remove('open')}
function recordScore(score){const b=getBoard();b.push({name:profile.name,score,date:Date.now()});b.sort((a,c)=>c.score-a.score);localStorage.setItem(LKEY,JSON.stringify(b.slice(0,30)))}function getBoard(){return JSON.parse(localStorage.getItem(LKEY)||'[]')}
function shareScene(){const code=btoa(unescape(encodeURIComponent(JSON.stringify(state.scene.map(({x,y,z,type})=>[x,y,z,type])))));const url=location.origin+location.pathname+'#build='+encodeURIComponent(code);navigator.share?navigator.share({title:'BlockForge build',url}).catch(()=>{}):navigator.clipboard?.writeText(url);toast(txt('Share link copied.','Linkul a fost copiat.'))}
function loadHash(){const m=location.hash.match(/build=([^&]+)/);if(!m)return;try{const arr=JSON.parse(decodeURIComponent(escape(atob(decodeURIComponent(m[1])))));state.scene=arr.map(([x,y,z,tp])=>({id:++uid,x,y,z,type:tp,hp:type(tp).hp}));render();toast(txt('Shared build loaded.','Construcția distribuită a fost încărcată.'))}catch{}}
function importJSON(e){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result),s=Array.isArray(d)?d:d.scene;if(!Array.isArray(s))throw 0;snapshot();state.scene=s.map(b=>({...b,id:++uid,hp:b.hp||type(b.type).hp}));render();toast('Imported')}catch{toast(txt('Invalid JSON.','JSON invalid.'))}};r.readAsText(f)}
function exportPNG(){const c=document.createElement('canvas'),ctx=c.getContext('2d');c.width=1200;c.height=800;ctx.fillStyle='#080914';ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='#fff';ctx.font='bold 54px sans-serif';ctx.fillText('BlockForge '+VERSION,60,80);state.scene.sort((a,b)=>a.z-b.z).forEach(b=>{const tp=type(b.type),x=300+(b.x-b.y)*42,y=540+(b.x+b.y)*18-b.z*38;ctx.fillStyle=tp.tone;ctx.fillRect(x,y,72,34);ctx.strokeStyle='rgba(255,255,255,.55)';ctx.strokeRect(x,y,72,34)});ctx.fillStyle='#a7abc6';ctx.font='24px sans-serif';ctx.fillText(`${profile.name} · ${state.score} pts`,60,750);const a=document.createElement('a');a.download='blockforge-build.png';a.href=c.toDataURL('image/png');a.click()}
function playReplay(){const frames=replay.length?replay:JSON.parse(localStorage.getItem(RKEY)||'[]');if(!frames.length)return toast(txt('No replay recorded.','Nu există reluare.'));clearInterval(replayTimer);let i=0;replayTimer=setInterval(()=>{state.scene=frames[i].scene.map(b=>({...b}));render();if(++i>=frames.length)clearInterval(replayTimer)},180)}
function applyAccess(){document.documentElement.classList.toggle('high-contrast',profile.settings.contrast);document.documentElement.classList.toggle('large-text',profile.settings.large);document.documentElement.classList.toggle('reduced-motion',profile.settings.motion);document.documentElement.classList.toggle('focus-visible',profile.settings.focus);ambient(profile.settings.music)}
function ambient(on){if(!on){window._bfAmbient?.stop?.();window._bfAmbient=null;return}if(window._bfAmbient)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.value=state.mode==='demolish'?72:state.mode==='survival'?92:110;g.gain.value=.012;o.connect(g).connect(audio.destination);o.start();window._bfAmbient=o}catch{}}
function gamepad(){let last=0;function loop(t){const gp=navigator.getGamepads?.()[0];if(gp&&t-last>180){if(gp.buttons[0]?.pressed){place(3,3);last=t}if(gp.buttons[1]?.pressed){setMode('demolish');last=t}if(gp.buttons[2]?.pressed){action('gravity');last=t}if(Math.abs(gp.axes[0]||0)>.5){state.spin+=(gp.axes[0]*3);applyCam()}}requestAnimationFrame(loop)}requestAnimationFrame(loop)}
function onboarding(){if(localStorage.getItem('bf.onboarded')){loadHash();return}document.body.insertAdjacentHTML('beforeend',`<div class="onboarding"><div class="onboarding-card"><h2>BlockForge ${VERSION}</h2><p>${txt('Build, test and share structural creations in nine game modes.','Construiește, testează și distribuie creații structurale în nouă moduri de joc.')}</p><div class="premium-grid"><button data-onlang="en">English</button><button data-onlang="ro">Română</button></div><button id="startForge">${txt('Enter the Forge','Intră în atelier')}</button></div></div>`);qa('[data-onlang]').forEach(b=>b.onclick=()=>{state.lang=b.dataset.onlang;localStorage.setItem('bf.lang',state.lang);applyLanguage()});q('#startForge').onclick=()=>{localStorage.setItem('bf.onboarded','1');q('.onboarding').remove();loadHash()}}
function registerPWA(){if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e})}function installApp(){if(installPrompt){installPrompt.prompt();installPrompt=null}else toast(txt('Use the browser menu: Install app.','Folosește meniul browserului: Instalează aplicația.'))}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
addEventListener('DOMContentLoaded',inject);
})();