function bind(){
 $('#modeTabs').onclick=e=>{const b=e.target.closest('[data-mode]');if(b)setMode(b.dataset.mode)};
 $$('.toolbar [data-action],.mobile-actions [data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action));
 $$('[data-editor]').forEach(b=>b.onclick=()=>editor(b.dataset.editor));
 $$('.collapse').forEach(b=>b.onclick=()=>$('#'+b.dataset.collapse).classList.toggle('collapsed'));
 $('#langBtn').onclick=()=>{state.lang=state.lang==='en'?'ro':'en';localStorage.setItem('bf.lang',state.lang);applyLanguage();buildPalette();buildTools();render()};
 $('#themeBtn').onclick=()=>{const a=['neon','yard','space','ruins'];state.theme=a[(a.indexOf(state.theme)+1)%a.length];document.body.dataset.theme=state.theme;localStorage.setItem('bf.theme',state.theme);toast(state.theme)};
 $('#soundBtn').onclick=e=>e.currentTarget.textContent=e.currentTarget.textContent==='🔊'?'🔇':'🔊';
 $('#photoBtn').onclick=()=>{document.body.classList.toggle('photo-mode');toast(tr('Photo mode: tap 📸 or press Esc to exit','Mod foto: apasă 📸 sau Esc pentru ieșire'))};
 $('#dailyBtn').onclick=startDaily;$('#tutorialBtn').onclick=startTutorial;
 el.stage.onpointerdown=e=>{if(e.target!==el.stage&&e.target!==el.world)return;drag={x:e.clientX,y:e.clientY,spin:state.spin,tilt:state.tilt};el.stage.setPointerCapture?.(e.pointerId)};
 addEventListener('pointermove',e=>{if(!drag)return;state.spin=drag.spin+(e.clientX-drag.x)*.35;state.tilt=Math.max(20,Math.min(84,drag.tilt-(e.clientY-drag.y)*.25));applyCam()});
 addEventListener('pointerup',()=>{drag=null;paint=false});
 el.stage.onwheel=e=>{e.preventDefault();state.zoom=Math.max(.55,Math.min(1.7,state.zoom-e.deltaY*.001));applyCam()};
 addEventListener('keydown',e=>{if(e.key==='Escape')document.body.classList.remove('photo-mode');if(e.key==='Delete')removeSelected();if(e.key.toLowerCase()==='g')action('gravity');if(e.ctrlKey&&e.key.toLowerCase()==='z'){e.preventDefault();undo()}});
}
function applyLanguage(){document.documentElement.lang=state.lang;$('#langBtn').textContent=state.lang==='en'?'RO':'EN';$$('[data-i18n]').forEach(n=>n.textContent=t(n.dataset.i18n));}
function setMode(m){state.mode=m;state.running=false;clearInterval(hazardTimer);hazardTimer=null;$$('#modeTabs [data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));if(m==='demolish')state.gravity=true;if(m==='campaign')state.level=Math.min(state.level,CAMPAIGN.length-1);if(m==='survival')state.wave=0;updateHint();render()}
function updateHint(){const map={build:tr('Choose a block and tap a tile. Drag empty space to orbit.','Alege un bloc și apasă pe grilă. Trage spațiul liber pentru rotire.'),demolish:tr('Choose a demolition tool, then tap a block or tile.','Alege o unealtă de demolare, apoi apasă pe un bloc sau o celulă.'),challenge:tr('Start the run, then build the tallest stable tower within budget.','Pornește runda și construiește cel mai înalt turn stabil în buget.'),campaign:tr('Complete each level objective and earn three stars.','Completează obiectivele fiecărui nivel și obține trei stele.'),survival:tr('Build before the next hazard wave arrives.','Construiește înainte de următorul val de pericole.'),versus:tr('Player 1 builds, Player 2 demolishes, then roles swap.','Jucătorul 1 construiește, Jucătorul 2 demolează, apoi rolurile se schimbă.')};el.hint.textContent=map[state.mode]}
function actTile(x,y){if(state.mode==='demolish'||(state.mode==='versus'&&state.player===2))demolish(x,y);else place(x,y)}
function snapshot(){state.past.push(state.scene.map(b=>({...b})));if(state.past.length>60)state.past.shift();state.future=[]}
function place(x,y,id=state.active){if(state.mode==='challenge'&&!state.running)return toast(tr('Start the challenge first.','Pornește mai întâi provocarea.'));if(state.mode==='survival'&&!state.running)return toast(tr('Start survival first.','Pornește mai întâi supraviețuirea.'));const z=heightAt(x,y);if(z>=MAX_Z)return toast(tr('Maximum height reached.','Înălțime maximă atinsă.'));const tp=type(id);if(['challenge','campaign'].includes(state.mode)&&state.running&&tp.cost>state.budget)return toast(tr('Not enough budget.','Buget insuficient.'));snapshot();state.scene.push({id:++uid,x,y,z,type:id,hp:tp.hp,spawn:true});if(state.running&&['challenge','campaign'].includes(state.mode))state.budget-=tp.cost;repairNeighbors(x,y,id);beep(220+z*40);buzz();render();checkObjectives()}
function repairNeighbors(x,y,id){if(type(id).power!=='repair')return;state.scene.filter(b=>Math.abs(b.x-x)+Math.abs(b.y-y)===1).forEach(b=>b.hp=Math.min(type(b.type).hp,b.hp+1))}
function demolish(x,y){const targets=column(x,y);if(!targets.length&&state.tool!=='quake')return toast(tr('Nothing to demolish there.','Nu există nimic de demolat acolo.'));snapshot();state.hits++;let affected=[];if(state.tool==='ball')affected=[...targets].sort((a,b)=>b.z-a.z).slice(0,2);if(state.tool==='hammer')affected=[...targets].sort((a,b)=>b.z-a.z).slice(0,1);if(state.tool==='laser')affected=state.scene.filter(b=>b.x===x);if(state.tool==='bomb'||state.tool==='meteor')affected=state.scene.filter(b=>Math.abs(b.x-x)+Math.abs(b.y-y)<= (state.tool==='meteor'?2:1));if(state.tool==='quake')affected=state.scene.filter(b=>b.z>0||Math.random()<.35);const dmg={ball:3,hammer:2,laser:4,bomb:4,meteor:6,quake:2}[state.tool];affected.forEach(b=>{if(type(b.type).power==='indestructible'&&state.tool!=='meteor')return;b.hp-=dmg;if(type(b.type).power==='explosive'&&b.hp<=0){state.scene.filter(n=>Math.abs(n.x-b.x)+Math.abs(n.y-b.y)<=1).forEach(n=>n.hp-=2)}});const dead=state.scene.filter(b=>b.hp<=0);dead.forEach(b=>burst(b.x,b.y,b.z,type(b.type).tone));state.scene=state.scene.filter(b=>b.hp>0);state.destroyed+=dead.length;state.combo=dead.length?Math.min(8,state.combo+Math.floor(dead.length/2)):1;state.maxCombo=Math.max(state.maxCombo,state.combo);settle();hazardFlash();beep(90,.18);buzz(70);render();checkObjectives();if(state.mode==='versus')advanceVersus()}
function settle(){if(!state.gravity)return;for(let x=0;x<SIZE;x++)for(let y=0;y<SIZE;y++){column(x,y).sort((a,b)=>a.z-b.z).forEach((b,i)=>b.z=i)}}
function unstableCount(){return state.scene.filter(b=>b.z>0&&!at(b.x,b.y,b.z-1)&&type(b.type).power!=='magnetic').length}
function calcScore(){const h=Math.max(0,...state.scene.map(b=>b.z+1)),stable=state.scene.length?1-unstableCount()/state.scene.length:1,mass=state.scene.reduce((s,b)=>s+type(b.type).mass,0);return Math.round(h*h*100*stable*(1+state.destroyed*.08)*state.combo/(1+mass*.02))}
function action(a){if(a==='undo')undo();if(a==='redo')redo();if(a==='gravity'){state.gravity=!state.gravity;$('#gravityLabel').textContent=state.gravity?'ON':'OFF';if(state.gravity)settle();render()}if(a==='clear'){snapshot();state.scene=[];state.selected.clear();render()}if(a==='demo')demo();if(a==='save'){localStorage.setItem(STORE,JSON.stringify(state.scene));toast(tr('Scene saved.','Scenă salvată.'))}if(a==='load'){try{const s=JSON.parse(localStorage.getItem(STORE)||'[]');snapshot();state.scene=s;uid=Math.max(uid,...s.map(b=>b.id||0));render()}catch{toast(tr('Saved scene is invalid.','Scena salvată nu este validă.'))}}if(a==='export')exportJSON()}
function undo(){if(!state.past.length)return;state.future.push(state.scene.map(b=>({...b})));state.scene=state.past.pop();render()}function redo(){if(!state.future.length)return;state.past.push(state.scene.map(b=>({...b})));state.scene=state.future.pop();render()}
