(()=>{
'use strict';
const K='bf.localSuite.v1',H='bf.history.v1',CUSTOM='bf.customBlocks.v1',LEVELS='bf.levelPacks.v1';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const lang=()=>state.lang==='ro';
const tr=(en,ro)=>lang()?ro:en;
let data=JSON.parse(localStorage.getItem(K)||'null')||{coins:0,seasonDay:1,streak:0,profiles:[{name:'Architect',score:0}],tournament:[],checkpoints:[],customBlocks:[],levelPacks:[],settings:{lowPower:false,colorBlind:false,narrator:false,voice:false,autoSave:true},stats:{rounds:0,placed:0,destroyed:0,byMode:{},byTool:{},byBlock:{},heat:{}}};
let replayGhost=[],timer=null,moves=0,speedStart=0,selectedExperiment='wind',history=JSON.parse(localStorage.getItem(H)||'[]');
const save=()=>localStorage.setItem(K,JSON.stringify(data));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function initLocal(){
 document.body.insertAdjacentHTML('beforeend',`<button id="localLabBtn" class="local-lab-btn" type="button">🧪 <span>${tr('Local Lab','Laborator local')}</span></button><aside id="localLab" class="local-lab" aria-label="Local Lab"><header><div><small>BLOCKFORGE 4.0</small><h2>${tr('Offline Systems Lab','Laborator sisteme offline')}</h2></div><button id="closeLocal" type="button">✕</button></header><nav id="localTabs"></nav><div id="localContent" class="local-content"></div></aside><div id="guidedTour" class="guided-tour" hidden></div>`);
 $('#localLabBtn').onclick=()=>openLocal('modes');$('#closeLocal').onclick=()=>$('#localLab').classList.remove('open');
 buildTabs();hookEngine();restoreSession();diagnose();
 addEventListener('beforeunload',()=>{if(data.settings.autoSave)recoverySave()});
 addEventListener('error',e=>logError(e.message));
 setInterval(()=>{if(data.settings.autoSave)recoverySave()},15000);
}
const tabs=[['modes','🎮', 'Modes','Moduri'],['physics','⚖️','Physics','Fizică'],['create','🛠️','Creators','Creatori'],['tourney','🏟️','Tournament','Turneu'],['data','💾','Data','Date'],['stats','📊','Stats','Statistici'],['access','♿','Access','Accesibilitate']];
function buildTabs(){const n=$('#localTabs');n.innerHTML=tabs.map(([id,ic,en,ro])=>`<button data-ltab="${id}" type="button">${ic}<span>${tr(en,ro)}</span></button>`).join('');n.onclick=e=>{const b=e.target.closest('[data-ltab]');if(b)openLocal(b.dataset.ltab)}}
function openLocal(tab){$('#localLab').classList.add('open');$$('[data-ltab]').forEach(b=>b.classList.toggle('active',b.dataset.ltab===tab));const views={modes:modesView,physics:physicsView,create:createView,tourney:tourneyView,data:dataView,stats:statsView,access:accessView};$('#localContent').innerHTML=views[tab]();bindLocal(tab)}
function modesView(){return `<section class="lab-grid">${[
 ['speed','⏱️','Speed Build','Construire contra-cronometru'],['precision','🎯','Precision Build','Construire de precizie'],['limited','🔢','Limited Moves','Mișcări limitate'],['single','1️⃣','One Material','Un singur material'],['nogravity','🚫','No Gravity','Fără gravitație'],['reverse','⬆️','Reverse Gravity','Gravitație inversă'],['fog','🌫️','Fog Mode','Mod ceață'],['memory','🧠','Memory Build','Construire din memorie'],['wind','🌬️','Wind Tunnel','Tunel de vânt'],['quake','🌋','Earthquake Lab','Laborator cutremur']
 ].map(x=>`<button class="lab-card" data-special="${x[0]}" type="button"><b>${x[1]} ${tr(x[2],x[3])}</b><small>${specialDescription(x[0])}</small></button>`).join('')}</section><section class="lab-section"><h3>${tr('Deterministic challenges','Provocări deterministe')}</h3><div class="inline"><input id="seedInput" placeholder="Seed" value="${dailySeed()}"><button data-act="seed">${tr('Generate','Generează')}</button><button data-act="weekly">${tr('Weekly contract','Contract săptămânal')}</button></div></section>`}
function specialDescription(id){const d={speed:['Build before time expires.','Construiește înainte de expirarea timpului.'],precision:['Match a generated blueprint.','Reproduce o schiță generată.'],limited:['Complete the tower with 20 actions.','Finalizează turnul în 20 de acțiuni.'],single:['Only one material is available.','Este disponibil un singur material.'],nogravity:['Floating structures remain suspended.','Structurile plutitoare rămân suspendate.'],reverse:['Top blocks pull the structure upward.','Blocurile superioare trag structura în sus.'],fog:['Only a small focus zone is visible.','Este vizibilă doar o zonă restrânsă.'],memory:['Memorize the structure, then rebuild it.','Memorează structura, apoi reconstruiește-o.'],wind:['Test lateral structural resistance.','Testează rezistența laterală.'],quake:['Control frequency and amplitude.','Controlează frecvența și amplitudinea.']};return tr(...d[id])}
function physicsView(){const c=centerOfMass(),pressure=pressureMap();return `<section class="lab-section"><h3>${tr('Structural inspector','Inspector structural')}</h3><div class="metric-row"><div><b>${c.x.toFixed(2)}, ${c.y.toFixed(2)}</b><small>${tr('Center of mass','Centru de greutate')}</small></div><div><b>${Math.max(0,...Object.values(pressure))}</b><small>${tr('Peak load','Sarcină maximă')}</small></div><div><b>${unstableCount()}</b><small>${tr('Unsupported','Fără suport')}</small></div></div><div class="pressure-map">${Array.from({length:64},(_,i)=>{const x=i%8,y=Math.floor(i/8),p=pressure[x+','+y]||0;return `<i title="${x},${y}: ${p}" style="--p:${Math.min(1,p/20)}"></i>`}).join('')}</div></section><section class="lab-section"><h3>${tr('Experiment controls','Comenzi experiment')}</h3><div class="inline"><select id="experiment"><option value="wind">Wind</option><option value="quake">Quake</option><option value="reverse">Reverse gravity</option></select><label>${tr('Intensity','Intensitate')} <input id="intensity" type="range" min="1" max="10" value="5"></label><button data-act="previewDamage">${tr('Damage preview','Previzualizare damage')}</button><button data-act="runExperiment">▶ ${tr('Run','Pornește')}</button></div><div id="damageReport" class="report"></div></section>`}
function createView(){return `<section class="lab-section"><h3>${tr('Custom block creator','Creator bloc personalizat')}</h3><div class="form-grid"><input id="cbName" placeholder="${tr('Name','Nume')}"><input id="cbColor" type="color" value="#35d6ff"><label>Mass<input id="cbMass" type="number" min=".5" max="10" step=".5" value="2"></label><label>HP<input id="cbHp" type="number" min="1" max="20" value="4"></label><label>Cost<input id="cbCost" type="number" min="1" max="20" value="3"></label><select id="cbPower"><option value="solid">Solid</option><option value="repair">Repair</option><option value="explosive">Explosive</option><option value="magnetic">Magnetic</option><option value="light">Light</option></select></div><button data-act="createBlock">＋ ${tr('Create block','Creează bloc')}</button><div class="mini-list">${data.customBlocks.map((b,i)=>`<span style="--tone:${b.tone}">${esc(b.name)} · m${b.mass} · hp${b.hp}<button data-delete-block="${i}">×</button></span>`).join('')}</div></section><section class="lab-section"><h3>${tr('Level creator','Creator de niveluri')}</h3><div class="form-grid"><input id="lvlName" placeholder="${tr('Level name','Nume nivel')}"><label>${tr('Target height','Înălțime țintă')}<input id="lvlH" type="number" min="1" max="8" value="5"></label><label>${tr('Max blocks','Maxim blocuri')}<input id="lvlMax" type="number" min="5" max="64" value="24"></label><label>${tr('Move limit','Limită mișcări')}<input id="lvlMoves" type="number" min="5" max="100" value="30"></label></div><button data-act="saveLevel">💾 ${tr('Save level pack','Salvează pachet')}</button><button data-act="exportLevels">⬇ ${tr('Export pack','Exportă pachet')}</button><div class="mini-list">${data.levelPacks.map((l,i)=>`<span>${esc(l.name)} · H${l.height} · ${l.max} blocks<button data-play-level="${i}">▶</button></span>`).join('')}</div></section>`}
function tourneyView(){return `<section class="lab-section"><h3>${tr('Local tournament','Turneu local')}</h3><div class="inline"><input id="playerName" placeholder="${tr('Player name','Nume jucător')}"><button data-act="addPlayer">＋</button><button data-act="startTournament">🏁 ${tr('Start bracket','Pornește tabloul')}</button></div><div class="players">${data.tournament.map((p,i)=>`<span>${esc(p.name)} <button data-remove-player="${i}">×</button></span>`).join('')}</div><div class="bracket">${renderBracket()}</div></section><section class="lab-section"><h3>${tr('Multi-profile local leaderboard','Clasament local multiprofil')}</h3>${data.profiles.sort((a,b)=>b.score-a.score).map((p,i)=>`<div class="score-row"><b>#${i+1} ${esc(p.name)}</b><span>${p.score}</span></div>`).join('')}</section>`}
function dataView(){return `<section class="lab-section"><h3>${tr('Challenge code','Cod provocare')}</h3><textarea id="challengeCode" readonly>${makeCode()}</textarea><div class="inline"><button data-act="copyCode">📋 ${tr('Copy','Copiază')}</button><button data-act="shareCode">↗ ${tr('Share','Distribuie')}</button><button data-act="loadCode">📥 ${tr('Load code','Încarcă cod')}</button></div><textarea id="codeInput" placeholder="${tr('Paste challenge code','Lipește codul provocării')}"></textarea></section><section class="lab-section"><h3>${tr('Checkpoints and recovery','Checkpoint-uri și recuperare')}</h3><div class="inline"><button data-act="checkpoint">🔖 ${tr('Add checkpoint','Adaugă checkpoint')}</button><button data-act="recover">♻️ ${tr('Recover session','Recuperează sesiunea')}</button><button data-act="fullBackup">⬇ ${tr('Full backup','Backup complet')}</button><label class="file-btn">⬆ ${tr('Import backup','Importă backup')}<input id="backupFile" type="file" accept="application/json"></label></div><div class="mini-list">${data.checkpoints.map((c,i)=>`<span>${new Date(c.date).toLocaleTimeString()} · ${c.scene.length} blocks <button data-load-checkpoint="${i}">↩</button></span>`).join('')}</div></section><section class="lab-section"><h3>${tr('Replay timeline','Cronologie replay')}</h3><input id="timeline" type="range" min="0" max="${Math.max(0,replayGhost.length-1)}" value="${Math.max(0,replayGhost.length-1)}"><div class="inline"><button data-act="ghost">👻 Ghost</button><button data-act="exportReplay">⬇ Replay JSON</button><button data-act="bookmark">🔖 Bookmark</button></div></section>`}
function statsView(){const s=data.stats;return `<section class="lab-section"><h3>${tr('Detailed local statistics','Statistici locale detaliate')}</h3><div class="metric-row"><div><b>${s.rounds}</b><small>${tr('Rounds','Runde')}</small></div><div><b>${s.placed}</b><small>${tr('Placed','Plasate')}</small></div><div><b>${s.destroyed}</b><small>${tr('Destroyed','Distruse')}</small></div><div><b>${data.coins}</b><small>Coins</small></div></div><h3>${tr('Usage heatmap','Heatmap utilizare')}</h3><div class="pressure-map">${Array.from({length:64},(_,i)=>{const x=i%8,y=Math.floor(i/8),v=s.heat[x+','+y]||0;return `<i title="${x},${y}: ${v}" style="--p:${Math.min(1,v/12)}"></i>`}).join('')}</div><h3>${tr('Round history','Istoric runde')}</h3><div class="history">${history.slice(-12).reverse().map(r=>`<div><b>${r.mode} · ${r.score}</b><small>${new Date(r.date).toLocaleString()} · H${r.height} · ${r.blocks} blocks</small></div>`).join('')||'<small>No rounds yet.</small>'}</div><button data-act="scoreCard">🖼️ ${tr('Export score card','Exportă card de scor')}</button></section>`}
function accessView(){return `<section class="lab-section"><h3>${tr('Accessibility and performance','Accesibilitate și performanță')}</h3>${toggle('lowPower','⚡',tr('Low-performance mode','Mod performanță redusă'))}${toggle('colorBlind','◩',tr('Color-blind patterns','Modele pentru daltonism'))}${toggle('narrator','🔈',tr('Text narrator','Narator text'))}${toggle('voice','🎙️',tr('Voice commands','Comenzi vocale'))}${toggle('autoSave','💾',tr('Automatic recovery save','Salvare automată pentru recuperare'))}<div class="inline"><button data-act="benchmark">📱 Benchmark</button><button data-act="diagnostic">🩺 Diagnostic</button><button data-act="tour">🧭 Guided tour</button></div><div id="diag" class="report"></div></section><section class="lab-section"><h3>${tr('Mobile controls','Controale mobile')}</h3><label>${tr('Interface scale','Scară interfață')} <input id="uiScale" type="range" min="80" max="130" value="100"></label><label>${tr('Touch button size','Dimensiune butoane tactile')} <input id="touchSize" type="range" min="40" max="72" value="48"></label></section>`}
function toggle(k,ic,label){return `<label class="setting"><span>${ic} ${label}</span><input type="checkbox" data-setting="${k}" ${data.settings[k]?'checked':''}></label>`}
function bindLocal(tab){
 $$('[data-special]').forEach(b=>b.onclick=()=>startSpecial(b.dataset.special));
 $$('[data-act]').forEach(b=>b.onclick=()=>localAction(b.dataset.act));
 $$('[data-setting]').forEach(i=>i.onchange=()=>{data.settings[i.dataset.setting]=i.checked;save();applyLocalSettings();if(i.dataset.setting==='voice'&&i.checked)startVoice()});
 $$('[data-delete-block]').forEach(b=>b.onclick=()=>{data.customBlocks.splice(+b.dataset.deleteBlock,1);save();openLocal('create')});
 $$('[data-play-level]').forEach(b=>b.onclick=()=>playLevel(+b.dataset.playLevel));
 $$('[data-remove-player]').forEach(b=>b.onclick=()=>{data.tournament.splice(+b.dataset.removePlayer,1);save();openLocal('tourney')});
 $$('[data-load-checkpoint]').forEach(b=>b.onclick=()=>loadCheckpoint(+b.dataset.loadCheckpoint));
 $('#timeline')?.addEventListener('input',e=>showReplay(+e.target.value));
 $('#backupFile')?.addEventListener('change',importBackup);
 $('#uiScale')?.addEventListener('input',e=>document.documentElement.style.fontSize=e.target.value+'%');
 $('#touchSize')?.addEventListener('input',e=>document.documentElement.style.setProperty('--touch',e.target.value+'px'));
}
function startSpecial(id){state.mode='build';state.scene=[];state.gravity=!['nogravity','reverse'].includes(id);moves=0;speedStart=Date.now();document.body.dataset.special=id;clearInterval(timer);if(id==='single'){state.active='core';$$('#palette .chip').forEach((b,i)=>b.hidden=i>0)}else $$('#palette .chip').forEach(b=>b.hidden=false);if(id==='memory'||id==='precision'){demo();replayGhost=state.scene.map(b=>({...b}));if(id==='memory')setTimeout(()=>{state.scene=[];render()},4500);else state.scene=[]}if(id==='speed')timer=setTimeout(()=>finishSpecial(id),60000);if(id==='fog')document.body.classList.add('fog-mode');else document.body.classList.remove('fog-mode');render();toast(specialDescription(id));$('#localLab').classList.remove('open')}
function finishSpecial(id){clearInterval(timer);const h=Math.max(0,...state.scene.map(b=>b.z+1));const score=calcScore()+Math.max(0,60000-(Date.now()-speedStart))/100;recordRound(id,Math.round(score));toast(tr(`Mode complete · height ${h}`,`Mod finalizat · înălțime ${h}`))}
function localAction(a){
 if(a==='seed')generateSeed($('#seedInput').value);if(a==='weekly')generateSeed('W'+weekNumber());
 if(a==='runExperiment')runExperiment();if(a==='previewDamage')previewDamage();if(a==='createBlock')createBlock();if(a==='saveLevel')saveLevel();if(a==='exportLevels')download('blockforge-level-pack.json',JSON.stringify(data.levelPacks,null,2));
 if(a==='addPlayer')addPlayer();if(a==='startTournament')startTournament();if(a==='copyCode')navigator.clipboard?.writeText(makeCode());if(a==='shareCode')shareCode();if(a==='loadCode')loadCode($('#codeInput').value.trim());
 if(a==='checkpoint')addCheckpoint();if(a==='recover')restoreSession(true);if(a==='fullBackup')fullBackup();if(a==='ghost')toggleGhost();if(a==='exportReplay')download('blockforge-replay.json',JSON.stringify(replayGhost,null,2));if(a==='bookmark')addCheckpoint();
 if(a==='benchmark')benchmark();if(a==='diagnostic')diagnose(true);if(a==='tour')guidedTour();if(a==='scoreCard')scoreCard();
}
function hookEngine(){
 const oldPlace=window.place,oldDemolish=window.demolish,oldFinish=window.finishRun,oldSnapshot=window.snapshot;
 window.place=function(x,y,id){moves++;data.stats.placed++;data.stats.heat[x+','+y]=(data.stats.heat[x+','+y]||0)+1;data.stats.byBlock[id||state.active]=(data.stats.byBlock[id||state.active]||0)+1;save();if(document.body.dataset.special==='limited'&&moves>20)return toast(tr('Move limit reached.','Limita de mișcări a fost atinsă.'));return oldPlace(x,y,id)};
 window.demolish=function(x,y){data.stats.byTool[state.tool]=(data.stats.byTool[state.tool]||0)+1;const before=state.scene.length,r=oldDemolish(x,y);data.stats.destroyed+=Math.max(0,before-state.scene.length);save();return r};
 window.snapshot=function(){oldSnapshot();replayGhost.push(state.scene.map(b=>({...b})));if(replayGhost.length>150)replayGhost.shift()};
 window.finishRun=function(){oldFinish();recordRound(state.mode,state.score)};
}
function recordRound(mode,score){data.stats.rounds++;data.stats.byMode[mode]=(data.stats.byMode[mode]||0)+1;data.coins+=Math.max(1,Math.round(score/500));const r={date:Date.now(),mode,score,height:Math.max(0,...state.scene.map(b=>b.z+1)),blocks:state.scene.length};history.push(r);if(history.length>100)history.shift();localStorage.setItem(H,JSON.stringify(history));save()}
function centerOfMass(){let mass=0,x=0,y=0;state.scene.forEach(b=>{const m=type(b.type)?.mass||1;mass+=m;x+=(b.x+.5)*m;y+=(b.y+.5)*m});return mass?{x:x/mass,y:y/mass}:{x:4,y:4}}
function pressureMap(){const p={};state.scene.forEach(b=>{const k=b.x+','+b.y;p[k]=(p[k]||0)+(type(b.type)?.mass||1)});return p}
function previewDamage(){const intensity=+$('#intensity').value,kind=$('#experiment').value;const affected=state.scene.filter(b=>kind==='wind'?b.z>2:kind==='quake'?b.z>0:true);$('#damageReport').innerHTML=`${affected.length} ${tr('blocks exposed','blocuri expuse')} · ${tr('estimated damage','damage estimat')} ${Math.round(affected.length*intensity*.35)}`}
function runExperiment(){const intensity=+$('#intensity').value,kind=$('#experiment').value;snapshot();state.scene.forEach(b=>{if(kind==='wind'&&b.z>2&&Math.random()<intensity/14)b.hp--;if(kind==='quake'&&b.z>0&&Math.random()<intensity/12)b.hp-=2;if(kind==='reverse'&&b.z===0&&Math.random()<intensity/15)b.hp--});state.scene=state.scene.filter(b=>b.hp>0);settle();render();hazardFlash()}
function createBlock(){const b={id:'custom_'+Date.now(),name:$('#cbName').value||'Custom',tone:$('#cbColor').value,mass:+$('#cbMass').value,hp:+$('#cbHp').value,cost:+$('#cbCost').value,power:$('#cbPower').value};data.customBlocks.push(b);BLOCKS.push({id:b.id,name:{en:b.name,ro:b.name},tone:b.tone,mass:b.mass,hp:b.hp,cost:b.cost,power:b.power});save();buildPalette();openLocal('create')}
function saveLevel(){data.levelPacks.push({name:$('#lvlName').value||'Custom level',height:+$('#lvlH').value,max:+$('#lvlMax').value,moves:+$('#lvlMoves').value,seed:Date.now()});save();openLocal('create')}
function playLevel(i){const l=data.levelPacks[i];if(!l)return;state.scene=[];state.mode='challenge';state.running=true;state.budget=l.max*2;moves=0;toast(`${l.name} · H${l.height} · ${l.moves} moves`);render();$('#localLab').classList.remove('open')}
function addPlayer(){const name=$('#playerName').value.trim();if(!name)return;data.tournament.push({name,score:0,round:1});data.profiles.push({name,score:0});save();openLocal('tourney')}
function startTournament(){if(data.tournament.length<2)return toast(tr('Add at least two players.','Adaugă cel puțin doi jucători.'));data.tournament.forEach((p,i)=>p.opponent=data.tournament[i%2?i-1:i+1]?.name||'BYE');save();openLocal('tourney')}
function renderBracket(){return data.tournament.map(p=>`<div><b>${esc(p.name)}</b><small>vs ${esc(p.opponent||'?')}</small></div>`).join('')}
function makeCode(){try{return btoa(unescape(encodeURIComponent(JSON.stringify(state.scene.map(({x,y,z,type})=>[x,y,z,type]))))).replace(/=+$/,'')}catch{return ''}}
function loadCode(code){try{const arr=JSON.parse(decodeURIComponent(escape(atob(code))));snapshot();state.scene=arr.map(a=>({id:++uid,x:a[0],y:a[1],z:a[2],type:a[3],hp:type(a[3])?.hp||3}));render();toast(tr('Challenge loaded.','Provocare încărcată.'))}catch{toast(tr('Invalid code.','Cod invalid.'))}}
function shareCode(){const text='BlockForge Challenge: '+makeCode();navigator.share?navigator.share({title:'BlockForge Challenge',text}):navigator.clipboard?.writeText(text)}
function addCheckpoint(){data.checkpoints.unshift({date:Date.now(),scene:state.scene.map(b=>({...b})),mode:state.mode});data.checkpoints=data.checkpoints.slice(0,12);save();openLocal('data')}
function loadCheckpoint(i){const c=data.checkpoints[i];if(!c)return;snapshot();state.scene=c.scene.map(b=>({...b}));state.mode=c.mode;render();$('#localLab').classList.remove('open')}
function recoverySave(){localStorage.setItem('bf.recovery',JSON.stringify({date:Date.now(),scene:state.scene,mode:state.mode,profile:data}))}
function restoreSession(show=false){try{const r=JSON.parse(localStorage.getItem('bf.recovery')||'null');if(!r)return;if(show||confirm(tr('Restore last BlockForge session?','Restabilești ultima sesiune BlockForge?'))){state.scene=r.scene||[];state.mode=r.mode||'build';render()}}catch{}}
function fullBackup(){download('blockforge-full-backup.json',JSON.stringify({version:4,date:Date.now(),scene:state.scene,data,history,replay:replayGhost,settings:{lang:state.lang,theme:state.theme}},null,2))}
function importBackup(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const b=JSON.parse(r.result);state.scene=b.scene||[];data=b.data||data;history=b.history||[];replayGhost=b.replay||[];save();localStorage.setItem(H,JSON.stringify(history));render();toast(tr('Backup imported.','Backup importat.'))}catch{toast(tr('Invalid backup.','Backup invalid.'))}};r.readAsText(f)}
function toggleGhost(){document.body.classList.toggle('ghost-replay');showReplay(replayGhost.length-1)}
function showReplay(i){const frame=replayGhost[i];if(!frame)return;let layer=$('#ghostLayer');if(!layer){layer=document.createElement('div');layer.id='ghostLayer';layer.className='ghost-layer';$('#world').append(layer)}layer.innerHTML='';frame.forEach(b=>{const d=document.createElement('i');d.style.cssText=`--x:${b.x*TILE-SIZE*TILE/2}px;--y:${b.y*TILE-SIZE*TILE/2}px;--z:${b.z*LIFT}px`;layer.append(d)})}
function benchmark(){const start=performance.now();let n=0;for(let i=0;i<200000;i++)n+=Math.sqrt(i);const ms=performance.now()-start;data.settings.lowPower=ms>25;save();applyLocalSettings();$('#diag').textContent=`${ms.toFixed(1)}ms · ${data.settings.lowPower?'LOW POWER':'FULL FX'}`}
function diagnose(show=false){const checks={localStorage:storageOK(),serviceWorker:'serviceWorker'in navigator,vibration:'vibrate'in navigator,speech:'speechSynthesis'in window,recognition:!!(window.SpeechRecognition||window.webkitSpeechRecognition),share:'share'in navigator,gamepad:'getGamepads'in navigator,online:navigator.onLine};if(show)$('#diag').innerHTML=Object.entries(checks).map(([k,v])=>`<span>${v?'✓':'○'} ${k}</span>`).join('');return checks}
function storageOK(){try{localStorage.setItem('_bf','1');localStorage.removeItem('_bf');return true}catch{return false}}
function logError(msg){const e=JSON.parse(localStorage.getItem('bf.errors')||'[]');e.push({date:Date.now(),msg});localStorage.setItem('bf.errors',JSON.stringify(e.slice(-20)))}
function applyLocalSettings(){document.body.classList.toggle('low-power',data.settings.lowPower);document.body.classList.toggle('colorblind',data.settings.colorBlind)}
function startVoice(){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R)return toast(tr('Voice recognition unavailable.','Recunoașterea vocală nu este disponibilă.'));const r=new R();r.continuous=true;r.lang=lang()?'ro-RO':'en-US';r.onresult=e=>{const s=e.results[e.results.length-1][0].transcript.toLowerCase();if(/undo|înapoi/.test(s))undo();if(/gravity|gravita/.test(s))action('gravity');if(/clear|șterge/.test(s))action('clear');if(/build|constru/.test(s))setMode('build');if(/demol/.test(s))setMode('demolish')};r.start()}
function guidedTour(){const steps=[['#modeTabs',tr('Choose a game mode.','Alege un mod de joc.')],['#palette',tr('Pick a material.','Alege un material.')],['#stage',tr('Tap the grid to build.','Apasă pe grilă pentru a construi.')],['#localLabBtn',tr('Open the offline systems lab.','Deschide laboratorul offline.')]];let i=0,g=$('#guidedTour');g.hidden=false;const next=()=>{if(i>=steps.length){g.hidden=true;return}const [sel,text]=steps[i++],r=$(sel)?.getBoundingClientRect();g.innerHTML=`<p>${text}</p><button>${tr('Next','Următorul')}</button>`;if(r){g.style.left=Math.min(innerWidth-260,r.left)+'px';g.style.top=Math.min(innerHeight-120,r.bottom+8)+'px'}g.querySelector('button').onclick=next};next()}
function scoreCard(){const c=document.createElement('canvas');c.width=1080;c.height=1080;const x=c.getContext('2d'),h=Math.max(0,...state.scene.map(b=>b.z+1));x.fillStyle='#080914';x.fillRect(0,0,c.width,c.height);x.fillStyle='#53f4ff';x.font='900 74px sans-serif';x.fillText('BLOCKFORGE',80,150);x.fillStyle='white';x.font='700 54px sans-serif';x.fillText(`${tr('Score','Scor')}: ${state.score}`,80,310);x.font='38px sans-serif';x.fillText(`${tr('Height','Înălțime')}: ${h}`,80,400);x.fillText(`${tr('Blocks','Blocuri')}: ${state.scene.length}`,80,470);x.fillText(`${tr('Mode','Mod')}: ${state.mode}`,80,540);x.fillStyle='#ffd166';x.font='700 42px sans-serif';x.fillText('laurandreea10.github.io',80,940);const a=document.createElement('a');a.href=c.toDataURL('image/png');a.download='blockforge-score-card.png';a.click()}
function generateSeed(seed){let n=[...String(seed)].reduce((s,c)=>s+c.charCodeAt(0),0);state.scene=[];for(let i=0;i<16;i++){n=(n*9301+49297)%233280;const x=2+n%4,y=2+Math.floor(n/7)%4,z=heightAt(x,y),tp=BLOCKS[n%BLOCKS.length];if(z<MAX_Z)state.scene.push({id:++uid,x,y,z,type:tp.id,hp:tp.hp})}render();toast(`Seed ${seed}`);$('#localLab').classList.remove('open')}
function dailySeed(){const d=new Date();return `${d.getFullYear()}-${d.getMonth()+1}-${d.getDate()}`}
function weekNumber(){const d=new Date(),s=new Date(d.getFullYear(),0,1);return Math.ceil((((d-s)/86400000)+s.getDay()+1)/7)}
function download(name,text){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
applyLocalSettings();
addEventListener('load',initLocal);
})();