(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],ro=()=>state.lang==='ro',tr=(e,r)=>ro()?r:e;
let engineer=false,cinemaTimer=null,cinemaIndex=0,frames=[],perf='auto',recording=null,chunks=[];
function inject(){document.body.insertAdjacentHTML('beforeend',`<div class="mobile-drawer-backdrop" id="drawerBack"></div><div class="engineer-dock"><button data-ref="engineer" title="Engineer View">📐</button><button data-ref="audit" title="Audit">✓</button><button data-ref="cinema" title="Cinema">🎬</button><button data-ref="access" title="Accessible view">👁</button><button data-ref="focus" title="Focus">◉</button><button data-ref="perf" title="Performance">⚡</button></div><aside class="engineer-panel" id="engineerPanel"></aside><div class="engineer-overlay" id="engineerOverlay"></div><div class="cinema-bar" id="cinemaBar"><button data-cine="prev">◀</button><button data-cine="play">▶</button><button data-cine="next">▶|</button><button data-cine="slow">½</button><button data-cine="record">●</button><button data-cine="close">✕</button></div>`);bindRefined();hookRender();restoreSettings();runBenchmark();}
function bindRefined(){$$('[data-ref]').forEach(b=>b.onclick=()=>refAction(b.dataset.ref));$('#engineerPanel').onclick=panelAction;$('#cinemaBar').onclick=cinemaAction;$('#mobileTools')?.addEventListener('click',openMobileTools);$('#drawerBack').onclick=closeMobileTools;addEventListener('keydown',e=>{if(e.key.toLowerCase()==='e')toggleEngineer();if(e.key.toLowerCase()==='v')toggleTop();if(e.key==='Escape'){closePanel();closeMobileTools()}});let pinch=null;$('#stage').addEventListener('touchstart',e=>{if(e.touches.length===2){const a=e.touches[0],b=e.touches[1];pinch={d:Math.hypot(a.clientX-b.clientX,a.clientY-b.clientY),z:state.zoom}}},{passive:true});$('#stage').addEventListener('touchmove',e=>{if(e.touches.length===2&&pinch){const a=e.touches[0],b=e.touches[1],d=Math.hypot(a.clientX-b.clientX,a.clientY-b.clientY);state.zoom=Math.max(.55,Math.min(1.7,pinch.z*d/pinch.d));applyCam()}},{passive:true});}
function hookRender(){const old=window.render;window.render=function(){old();if(engineer)paintEngineerOverlay();captureFrame();updateSceneDescription()};}
function refAction(a){if(a==='engineer')toggleEngineer();if(a==='audit')openAudit();if(a==='cinema')openCinema();if(a==='access')openAccess();if(a==='focus')document.body.classList.toggle('focus-mode');if(a==='perf')cyclePerf();}
function toggleEngineer(){engineer=!engineer;document.body.classList.toggle('engineer-view',engineer);engineer?openEngineer():($('#engineerOverlay').innerHTML='');}
function structural(){const cols=[];for(let x=0;x<SIZE;x++)for(let y=0;y<SIZE;y++){const c=column(x,y),load=c.reduce((s,b)=>s+type(b.type).mass,0),base=c.find(b=>b.z===0),cap=base?type(base.type).hp*4:0;if(c.length)cols.push({x,y,load,cap,risk:cap?Math.min(1,load/cap):1})}const mass=state.scene.reduce((s,b)=>s+type(b.type).mass,0)||1,cx=state.scene.reduce((s,b)=>s+(b.x+.5)*type(b.type).mass,0)/mass,cy=state.scene.reduce((s,b)=>s+(b.y+.5)*type(b.type).mass,0)/mass;return{cols,mass,cx,cy,unsupported:unstableCount(),maxRisk:Math.max(0,...cols.map(c=>c.risk))}}
function openEngineer(){const d=structural(),p=$('#engineerPanel');p.className='engineer-panel open';p.innerHTML=`<header><div><small>BLOCKFORGE 5.0</small><h2>${tr('Engineer View','Vedere inginer')}</h2></div><button data-close>✕</button></header><section><h3>${tr('Structural analysis','Analiză structurală')}</h3><div class="scene-description" id="sceneDescription"></div></section><section><div class="engineer-grid"><button data-panel="top">⬒ ${tr('Top view','Vedere sus')}</button><button data-panel="flat">▦ ${tr('2D view','Vedere 2D')}</button><button data-panel="forces">➜ ${tr('Forces','Forțe')}</button><button data-panel="predict">⚠ ${tr('Predict collapse','Prezice colaps')}</button></div></section><section><h3>${tr('Column loads','Sarcini coloane')}</h3><div class="force-list">${d.cols.sort((a,b)=>b.risk-a.risk).slice(0,12).map(c=>`<div class="force-row"><span>${c.x},${c.y}</span><i style="width:${Math.min(100,c.risk*100)}%"></i><b>${Math.round(c.risk*100)}%</b></div>`).join('')||'<small>—</small>'}</div></section><section><h3>${tr('Simulation','Simulare')}</h3><label>${tr('Wind direction','Direcție vânt')} <input id="windDir" type="range" min="0" max="359" value="90"></label><label>${tr('Force','Forță')} <input id="forceRange" type="range" min="1" max="10" value="4"></label><button data-panel="simulate">🌬 ${tr('Run stress test','Rulează testul')}</button></section>`;paintEngineerOverlay();updateSceneDescription();}
function paintEngineerOverlay(){const o=$('#engineerOverlay'),d=structural(),r=$('#stage').getBoundingClientRect();o.innerHTML='';d.cols.forEach(c=>{const m=document.createElement('i');m.className='load-marker';m.style.left=(r.left+r.width*(.31+c.x*.055))+'px';m.style.top=(r.top+r.height*(.62+c.y*.018))+'px';m.style.setProperty('--risk',c.risk>.8?'#ff516b':c.risk>.5?'#ffd166':'#67ff9b');o.append(m)});if(state.scene.length){const c=document.createElement('i');c.className='center-mass';c.style.left=(r.left+r.width*(.31+d.cx*.055))+'px';c.style.top=(r.top+r.height*(.62+d.cy*.018))+'px';o.append(c)}}
function updateSceneDescription(){const n=$('#sceneDescription');if(!n)return;const d=structural(),h=Math.max(0,...state.scene.map(b=>b.z+1));n.textContent=tr(`${state.scene.length} blocks, height ${h}, total mass ${d.mass.toFixed(1)}, ${d.unsupported} unsupported blocks. Highest structural risk ${Math.round(d.maxRisk*100)}%. Center of mass at ${d.cx.toFixed(1)}, ${d.cy.toFixed(1)}.`,`${state.scene.length} blocuri, înălțime ${h}, masă totală ${d.mass.toFixed(1)}, ${d.unsupported} blocuri fără suport. Risc structural maxim ${Math.round(d.maxRisk*100)}%. Centrul de masă la ${d.cx.toFixed(1)}, ${d.cy.toFixed(1)}.`)}
function panelAction(e){if(e.target.closest('[data-close]'))closePanel();const a=e.target.closest('[data-panel]')?.dataset.panel;if(a==='top')toggleTop();if(a==='flat')document.body.classList.toggle('flat-view');if(a==='forces')paintEngineerOverlay();if(a==='predict')predict();if(a==='simulate')stressTest();}
function toggleTop(){document.body.classList.toggle('top-view')}
function predict(){const d=structural(),bad=d.cols.filter(c=>c.risk>.75).sort((a,b)=>b.risk-a.risk)[0];toast(bad?tr(`Likely failure near column ${bad.x},${bad.y}.`,`Colaps probabil lângă coloana ${bad.x},${bad.y}.`):tr('No critical collapse path detected.','Nu a fost detectată o cale critică de colaps.'))}
function stressTest(){const f=+$('#forceRange')?.value||4,dir=+$('#windDir')?.value||90,dx=Math.cos(dir*Math.PI/180),dy=Math.sin(dir*Math.PI/180);snapshot();state.scene.forEach(b=>{const exposure=(b.z+1)/MAX_Z,side=Math.abs(dx*(b.x-3.5)+dy*(b.y-3.5))/5;if(Math.random()<exposure*side*f*.09)b.hp-=Math.ceil(f/4)});state.scene=state.scene.filter(b=>b.hp>0);settle();render();toast(tr('Stress simulation complete.','Simularea structurală s-a încheiat.'))}
function openAudit(){const tests=runAudit(),p=$('#engineerPanel');p.className='engineer-panel open';p.innerHTML=`<header><div><small>QUALITY GATE</small><h2>${tr('System audit','Audit sistem')}</h2></div><button data-close>✕</button></header>${tests.map(t=>`<div class="audit-item"><span>${t.name}</span><b class="audit-${t.status}">${t.status.toUpperCase()}</b></div>`).join('')}<section><button data-panel="rerun">↻ ${tr('Run again','Rulează din nou')}</button><a href="./tests.html" class="wide">${tr('Open test suite','Deschide testele')}</a></section>`;}
function runAudit(){const test=(name,fn)=>{try{return{name,status:fn()?'pass':'fail'}}catch{return{name,status:'fail'}}};return[test('DOM controls',()=>$$('button').length>20),test('Game state',()=>Array.isArray(state.scene)),test('Block catalog',()=>BLOCKS.length>=7),test('Mode controls',()=>$$('[data-mode]').length>=9),test('Local storage',()=>{localStorage.setItem('bf.audit','1');return localStorage.getItem('bf.audit')==='1'}),test('PWA service worker',()=>('serviceWorker'in navigator)),test('Audio fallback',()=>!!(window.AudioContext||window.webkitAudioContext)),test('Responsive viewport',()=>innerWidth>0),test('Language system',()=>I18N.en&&I18N.ro),test('Recovery systems',()=>typeof localStorage!=='undefined')];}
function openAccess(){const p=$('#engineerPanel');p.className='engineer-panel open';p.innerHTML=`<header><div><small>ACCESS</small><h2>${tr('Accessible views','Vederi accesibile')}</h2></div><button data-close>✕</button></header><section><div class="engineer-grid"><button data-access="top">⬒ ${tr('Top view','Vedere sus')}</button><button data-access="flat">▦ ${tr('Flat materials','Materiale plate')}</button><button data-access="describe">🔊 ${tr('Describe scene','Descrie scena')}</button><button data-access="contrast">◐ ${tr('AAA contrast','Contrast AAA')}</button><button data-access="motion">≈ ${tr('Reduce motion','Redu mișcarea')}</button><button data-access="keys">⌨ ${tr('Keyboard help','Ajutor tastatură')}</button></div></section><section><p class="scene-description">E — Engineer View · V — top view · G — gravity · Delete — remove · Ctrl+Z — undo · Escape — close.</p></section>`;p.querySelectorAll('[data-access]').forEach(b=>b.onclick=()=>accessAction(b.dataset.access));}
function accessAction(a){if(a==='top')toggleTop();if(a==='flat')document.body.classList.toggle('flat-view');if(a==='contrast')document.body.classList.toggle('high-contrast');if(a==='motion')document.body.classList.toggle('reduce-motion');if(a==='describe'){const d=structural(),msg=$('#sceneDescription')?.textContent||tr(`${state.scene.length} blocks.`,` ${state.scene.length} blocuri.`);speechSynthesis?.speak(new SpeechSynthesisUtterance(msg))}if(a==='keys')toast('E · V · G · Delete · Ctrl+Z · Esc')}
function openCinema(){frames=JSON.parse(localStorage.getItem('bf.replay')||'[]');if(!frames.length)frames=[{scene:state.scene.map(b=>({...b}))}];cinemaIndex=frames.length-1;$('#cinemaBar').classList.add('show');document.body.classList.add('focus-mode')}
function cinemaAction(e){const a=e.target.closest('[data-cine]')?.dataset.cine;if(!a)return;if(a==='close'){clearInterval(cinemaTimer);$('#cinemaBar').classList.remove('show');document.body.classList.remove('focus-mode')}if(a==='prev')showFrame(Math.max(0,cinemaIndex-1));if(a==='next')showFrame(Math.min(frames.length-1,cinemaIndex+1));if(a==='play')playCinema(420);if(a==='slow')playCinema(900);if(a==='record')toggleRecord(e.target)}
function showFrame(i){cinemaIndex=i;const f=frames[i];if(f?.scene){state.scene=f.scene.map(b=>({...b}));render()}}
function playCinema(ms){clearInterval(cinemaTimer);cinemaIndex=0;cinemaTimer=setInterval(()=>{showFrame(cinemaIndex);cinemaIndex++;if(cinemaIndex>=frames.length)clearInterval(cinemaTimer)},ms)}
async function toggleRecord(btn){if(recording){recording.stop();recording=null;btn.textContent='●';return}try{const stream=await navigator.mediaDevices.getDisplayMedia({video:true,audio:false});recording=new MediaRecorder(stream);chunks=[];recording.ondataavailable=e=>chunks.push(e.data);recording.onstop=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(chunks,{type:'video/webm'}));a.download='blockforge-cinematic.webm';a.click();stream.getTracks().forEach(t=>t.stop())};recording.start();btn.textContent='■'}catch{toast(tr('Screen recording was not permitted.','Înregistrarea ecranului nu a fost permisă.'))}}
function captureFrame(){if(!state.scene)return;const last=frames[frames.length-1];const sig=JSON.stringify(state.scene.map(b=>[b.x,b.y,b.z,b.type,b.hp]));if(last?.sig===sig)return;frames.push({sig,scene:state.scene.map(b=>({...b}))});if(frames.length>180)frames.shift()}
function cyclePerf(){perf=perf==='auto'?'low':perf==='low'?'high':'auto';document.body.classList.toggle('performance-low',perf==='low');localStorage.setItem('bf.perf',perf);toast(`Performance: ${perf}`)}
function runBenchmark(){const start=performance.now();let x=0;for(let i=0;i<160000;i++)x+=Math.sqrt(i);const ms=performance.now()-start;if(perf==='auto'&&(ms>18||navigator.hardwareConcurrency<=4))document.body.classList.add('performance-low')}
function restoreSettings(){perf=localStorage.getItem('bf.perf')||'auto';document.body.classList.toggle('performance-low',perf==='low')}
function openMobileTools(){$('#leftPanel').classList.add('mobile-open');$('#drawerBack').classList.add('show')}
function closeMobileTools(){$('#leftPanel').classList.remove('mobile-open');$('#drawerBack').classList.remove('show')}
function closePanel(){$('#engineerPanel').classList.remove('open')}
init?inject():addEventListener('DOMContentLoaded',inject);
})();